backend:
  name: github
  repo: PerpetualStyle/www.perpetualstyle.co.za
  branch: main # or your default branch
  base_url: http://localhost:3000 # Your site URL
  auth_endpoint: /auth?site=www.perpetualstyle.co.za&redirect_uri=https%3A%2F%2Fwww.perpetualstyle.co.za%2Fadmin
media_folder: "static/images" # Folder for uploaded images
public_folder: "/images" # Public path for images
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts" # Folder where Markdown files are stored
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
