backend:
  name: github
  repo: PerpetualStyle/www.perpetualstyle.co.za
  branch: main # or your default branch
  auth:
    client_id: "Ov23li3lL1IFRemCcUIx" # Replace with your Client ID
    redirect_url: "https://www.perpetualstyle.co.za/admin"
  auth_scope: repo # Use implicit grant for GitHub Pages
  api_root: https://api.github.com
  base_url: https://github.com
  auth_endpoint: login/oauth/authorize?client_id=Ov23li3lL1IFRemCcUIx&redirect_uri=https%3A%2F%2Fwww.perpetualstyle.co.za%2Fadmin
media_folder: "static/images" # Folder for uploaded images
public_folder: "/images" # Public path for images
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts" # Folder where Markdown files are stored
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
