backend:
  name: github
  repo: PerpetualStyle/www.perpetualstyle.co.za
  branch: master # or your default branch
  auth_type: implicit # Use implicit grant for GitHub Pages
  app_id: Ov23li3lL1IFRemCcUIx # Replace with your Client ID
  api_root: https://api.github.com
  base_url: https://www.perpetualstyle.co.za # Your site URL
  auth_endpoint: https://github.com/login/oauth/authorize
media_folder: "static/images" # Folder for uploaded images
public_folder: "/images" # Public path for images
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts" # Folder where Markdown files are stored
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
